In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [3]:
df = pd.read_csv("Group 2 Job 1_2_3 _ Breast Cancer Dataset.csv")

In [4]:
df.head(5)

,Unnamed: 0,x.radius_mean,x.texture_mean,x.perimeter_mean,x.area_mean,x.smoothness_mean,x.compactness_mean,x.concavity_mean,x.concave_pts_mean,x.symmetry_mean,...,x.texture_worst,x.perimeter_worst,x.area_worst,x.smoothness_worst,x.compactness_worst,x.concavity_worst,x.concave_pts_worst,x.symmetry_worst,x.fractal_dim_worst,y
0,1,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,0.1885,...,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259,B
1,2,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,0.1967,...,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183,B
2,3,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,0.1815,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,B
3,4,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,0.1467,...,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169,B
4,5,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,0.1769,...,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409,B

In [5]:
print(df.shape)

(569, 32)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           569 non-null    int64
 1   x.radius_mean        569 non-null    float64
 2   x.texture_mean       569 non-null    float64
 3   x.perimeter_mean     569 non-null    float64
 4   x.area_mean          569 non-null    float64
 5   x.smoothness_mean    569 non-null    float64
 6   x.compactness_mean   569 non-null    float64
 7   x.concavity_mean     569 non-null    float64
 8   x.concave_pts_mean   569 non-null    float64
 9   x.symmetry_mean      569 non-null    float64
 10  x.fractal_dim_mean   569 non-null    float64
 11  x.radius_se          569 non-null    float64
 12  x.texture_se         569 non-null    float64
 13  x.perimeter_se       569 non-null    float64
 14  x.area_se            569 non-null    float64
 15  x.smoothness_se      569 non-null    float64
 16  x.compactness_se     569 non-null    float64
 17  x.concavity_se       569 non-null    float64
 18  x.concave_pts_se     569 non-null    float64
 19  x.symmetry_se        569 non-null    float64
 20  x.fractal_dim_se     569 non-null    float64
 21  x.radius_worst       569 non-null    float64
 22  x.texture_worst      569 non-null    float64
 23  x.perimeter_worst    569 non-null    float64
 24  x.area_worst         569 non-null    float64
 25  x.smoothness_worst   569 non-null    float64
 26  x.compactness_worst  569 non-null    float64
 27  x.concavity_worst    569 non-null    float64
 28  x.concave_pts_worst  569 non-null    float64
 29  x.symmetry_worst     569 non-null    float64
 30  x.fractal_dim_worst  569 non-null    float64
 31  y                    569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB
None

In [8]:
print(df.describe())

       Unnamed: 0  x.radius_mean  x.texture_mean  x.perimeter_mean  \
count  569.000000     569.000000      569.000000        569.000000
mean   285.000000      14.127292       19.289649         91.969033
std    164.400426       3.524049        4.301036         24.298981
min      1.000000       6.981000        9.710000         43.790000
25%    143.000000      11.700000       16.170000         75.170000
50%    285.000000      13.370000       18.840000         86.240000
75%    427.000000      15.780000       21.800000        104.100000
max    569.000000      28.110000       39.280000        188.500000

       x.area_mean  x.smoothness_mean  x.compactness_mean  x.concavity_mean  \
count   569.000000         569.000000          569.000000        569.000000
mean    654.889104           0.096360            0.104341          0.088799
std     351.914129           0.014064            0.052813          0.079720
min     143.500000           0.052630            0.019380          0.000000
25%     420.300000           0.086370            0.064920          0.029560
50%     551.100000           0.095870            0.092630          0.061540
75%     782.700000           0.105300            0.130400          0.130700
max    2501.000000           0.163400            0.345400          0.426800

       x.concave_pts_mean  x.symmetry_mean  ...  x.radius_worst  \
count          569.000000       569.000000  ...      569.000000
mean             0.048919         0.181162  ...       16.269190
std              0.038803         0.027414  ...        4.833242
min              0.000000         0.106000  ...        7.930000
25%              0.020310         0.161900  ...       13.010000
50%              0.033500         0.179200  ...       14.970000
75%              0.074000         0.195700  ...       18.790000
max              0.201200         0.304000  ...       36.040000

       x.texture_worst  x.perimeter_worst  x.area_worst  x.smoothness_worst  \
count       569.000000         569.000000    569.000000          569.000000
mean         25.677223         107.261213    880.583128            0.132369
std           6.146258          33.602542    569.356993            0.022832
min          12.020000          50.410000    185.200000            0.071170
25%          21.080000          84.110000    515.300000            0.116600
50%          25.410000          97.660000    686.500000            0.131300
75%          29.720000         125.400000   1084.000000            0.146000
max          49.540000         251.200000   4254.000000            0.222600

       x.compactness_worst  x.concavity_worst  x.concave_pts_worst  \
count           569.000000         569.000000           569.000000
mean              0.254265           0.272188             0.114606
std               0.157336           0.208624             0.065732
min               0.027290           0.000000             0.000000
25%               0.147200           0.114500             0.064930
50%               0.211900           0.226700             0.099930
75%               0.339100           0.382900             0.161400
max               1.058000           1.252000             0.291000

       x.symmetry_worst  x.fractal_dim_worst
count        569.000000           569.000000
mean           0.290076             0.083946
std            0.061867             0.018061
min            0.156500             0.055040
25%            0.250400             0.071460
50%            0.282200             0.080040
75%            0.317900             0.092080
max            0.663800             0.207500

[8 rows x 31 columns]

In [9]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   x.radius_mean        569 non-null    float64
 1   x.texture_mean       569 non-null    float64
 2   x.perimeter_mean     569 non-null    float64
 3   x.area_mean          569 non-null    float64
 4   x.smoothness_mean    569 non-null    float64
 5   x.compactness_mean   569 non-null    float64
 6   x.concavity_mean     569 non-null    float64
 7   x.concave_pts_mean   569 non-null    float64
 8   x.symmetry_mean      569 non-null    float64
 9   x.fractal_dim_mean   569 non-null    float64
 10  x.radius_se          569 non-null    float64
 11  x.texture_se         569 non-null    float64
 12  x.perimeter_se       569 non-null    float64
 13  x.area_se            569 non-null    float64
 14  x.smoothness_se      569 non-null    float64
 15  x.compactness_se     569 non-null    float64
 16  x.concavity_se       569 non-null    float64
 17  x.concave_pts_se     569 non-null    float64
 18  x.symmetry_se        569 non-null    float64
 19  x.fractal_dim_se     569 non-null    float64
 20  x.radius_worst       569 non-null    float64
 21  x.texture_worst      569 non-null    float64
 22  x.perimeter_worst    569 non-null    float64
 23  x.area_worst         569 non-null    float64
 24  x.smoothness_worst   569 non-null    float64
 25  x.compactness_worst  569 non-null    float64
 26  x.concavity_worst    569 non-null    float64
 27  x.concave_pts_worst  569 non-null    float64
 28  x.symmetry_worst     569 non-null    float64
 29  x.fractal_dim_worst  569 non-null    float64
 30  y                    569 non-null    object
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [11]:
df.sample(5)

,x.radius_mean,x.texture_mean,x.perimeter_mean,x.area_mean,x.smoothness_mean,x.compactness_mean,x.concavity_mean,x.concave_pts_mean,x.symmetry_mean,x.fractal_dim_mean,...,x.texture_worst,x.perimeter_worst,x.area_worst,x.smoothness_worst,x.compactness_worst,x.concavity_worst,x.concave_pts_worst,x.symmetry_worst,x.fractal_dim_worst,y
464,15.12,16.68,98.78,716.6,0.08876,0.09588,0.07550,0.04079,0.1594,0.05986,...,20.24,117.70,989.5,0.1491,0.3331,0.33270,0.12520,0.3415,0.09740,M
126,11.50,18.45,73.28,407.4,0.09345,0.05991,0.02638,0.02069,0.1834,0.05934,...,22.46,83.12,508.9,0.1183,0.1049,0.08105,0.06544,0.2740,0.06487,B
154,12.46,19.89,80.43,471.3,0.08451,0.10140,0.06830,0.03099,0.1781,0.06249,...,23.07,88.13,551.3,0.1050,0.2158,0.19040,0.07625,0.2685,0.07764,B
255,12.87,19.54,82.67,509.2,0.09136,0.07883,0.01797,0.02090,0.1861,0.06347,...,24.38,95.14,626.9,0.1214,0.1652,0.07127,0.06384,0.3313,0.07735,B
538,17.27,25.42,112.40,928.8,0.08331,0.11090,0.12040,0.05736,0.1467,0.05407,...,35.46,132.80,1284.0,0.1436,0.4122,0.50360,0.17390,0.2500,0.07944,M

In [12]:
df['y'] = df['y'].map({'M':1, 'B':0})

In [13]:
df['y']

0      0
1      0
2      0
3      0
4      0
      ..
564    1
565    1
566    1
567    1
568    1
Name: y, Length: 569, dtype: int64

In [14]:
df['y'].value_counts()

y
0    357
1    212
Name: count, dtype: int64

In [15]:
df.isnull().sum()

x.radius_mean          0
x.texture_mean         0
x.perimeter_mean       0
x.area_mean            0
x.smoothness_mean      0
x.compactness_mean     0
x.concavity_mean       0
x.concave_pts_mean     0
x.symmetry_mean        0
x.fractal_dim_mean     0
x.radius_se            0
x.texture_se           0
x.perimeter_se         0
x.area_se              0
x.smoothness_se        0
x.compactness_se       0
x.concavity_se         0
x.concave_pts_se       0
x.symmetry_se          0
x.fractal_dim_se       0
x.radius_worst         0
x.texture_worst        0
x.perimeter_worst      0
x.area_worst           0
x.smoothness_worst     0
x.compactness_worst    0
x.concavity_worst      0
x.concave_pts_worst    0
x.symmetry_worst       0
x.fractal_dim_worst    0
y                      0
dtype: int64